### ISSUE TITLE
提交到upload.php的过程中出现问题

### ISSUE THREAD

**Issue by Jethro2002** [kesixin/Head_Cut_PC#1]
main.js第148行
case 'getCroppedCanvas':
          if (result) {
            var imgBase=result.toDataURL('image/jpeg');//这行出现问题，浏览器提示如下[1]
            var data={imgBase:imgBase};
            $.post('../upload.php',data,function(ret){
              if(ret=='true'){
                alert('上传成功');
              }else{
                alert('上传失败');
              }
            },'text');
          }

[1]:
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at HTMLButtonElement.<anonymous> (file:///C:/inetpub/wwwroot/%E5%9B%BE%E7%89%87%E8%A3%81%E5%89%AA/js/main.js:151:32)
    at HTMLDivElement.dispatch (file:///C:/inetpub/wwwroot/%E5%9B%BE%E7%89%87%E8%A3%81%E5%89%AA/js/jquery.min.js:3:28337)
    at HTMLDivElement.v.handle (file:///C:/inetpub/wwwroot/%E5%9B%BE%E7%89%87%E8%A3%81%E5%89%AA/js/jquery.min.js:3:25042)

**Comment by Jethro2002** [comment]
原因是php的临时目录没有设置到位。

解决方法如下：
-如果知道临时目录在哪
设置目录的权限
-不知道临时目录在哪
php.ini找到upload_tmp_dir把前面分号去掉，后面随便设置一个临时目录路径（这个目录一定要存在）
然后把这个路径的权限设置一下

接着就可以了！

**Comment by Jethro2002** [comment]
示例：upload_tmp_dir = c:/temp
